apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonus
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://root:@:5555/root/mkaddani-ops-demo.git
    path: manifests_will42/
    targetRevision: main
  syncPolicy:
    automated:
      prune: true