apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appx-gitlab
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: manifests_will42/
    repoURL: http://gitlab-webservice-default.gitlab.svc:8181/root/mkaddani-ops-demo.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

