apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mkaddani42/mkaddani-ops-demo.git
    path: manifests_will42/
    targetRevision: main
  syncPolicy:
    automated:
      prune: true