# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "akhalidS" do |akhalidS|
    akhalidS.vm.hostname = "akhalidS"
    akhalidS.vm.box = "debian/bullseye64"
    akhalidS.vm.network :private_network, ip: "192.168.56.110",  auto_config: false
    akhalidS.vm.provision "shell", path: "./scripts/server_setup.sh"
  end

  # Hypervisor Type2 Provider and settings - General on All the Above Machines:
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 1
 end
end