Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"

    config.vm.define "akhalidS" do |server|
        server.vm.hostname = "akhalidS"
        server.vm.network "private_network", ip: "192.168.56.110"
    
        server.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--name", "akhalidS"]
          vb.memory = "1024"
          vb.cpus = "1"
        end
        server.vm.provision "shell", path: "scripts/server.sh"
      end

end